version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 546200696978.dkr.ecr.us-east-1.amazonaws.com
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI=${REPOSITORY_URI}:${TAG}
  build:
    commands:
      - echo Build started on `date`
      - echo $IMAGE_URI
      - mvn install
      - docker build -t imageregistry .
      - docker tag imageregistry:latest 546200696978.dkr.ecr.us-east-1.amazonaws.com/imageregistry:latest
  post_build:
    commands:
      - printenv
      - docker push 546200696978.dkr.ecr.us-east-1.amazonaws.com/imageregistry:latest
      - echo Build completed on `date`
      - echo $(docker images)
      - echo Pushing docker image
      - echo push completed
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME 546200696978.dkr.ecr.us-east-1.amazonaws.com/imageregistry:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json