spring:
  data:
    mongodb:
      uri: mongodb://springmongotest:H5Po3DRrCEhedJU07Ink3R5WEM7sJSY9pgDSkLwlag077ISM1RXPJQEGgQxGlTLeRqpbDxi2Bm3yhTTx7NRKCA%3D%3D@springmongotest.mongo.cosmos.azure.com:10255/mydb?authSource=admin&replicaSet=globaldb&maxIdleTimeMS=120000&readPreference=primary&appname=MongoDB%20Compass&retryWrites=false&ssl=true
  application:
    name: movie-catalog-service
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: https://warm-plateau-82277.herokuapp.com/