spring:
  data:
    mongodb:
      uri: mongodb+srv://yasin:cimbom21@cluster0.f8enl.mongodb.net/movie
  application:
    name: movie-catalog-service
server:
  port: 8000
management:
  endpoints:
    web:
      base-path: /manage
loadbalancer:
  uri: ${loadbalancer_url}