spring:
  data:
    mongodb:
      uri: mongodb+srv://yasin:cimbom21@cluster0.f8enl.mongodb.net/mydb?authSource=admin&replicaSet=atlas-abz77t-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true
  application:
    name: movie-catalog-service
eureka:
  client:
    serviceUrl:
      defaultZone: https://warm-plateau-82277.herokuapp.com/eureka
