spring:
  data:
    mongodb:
      uri: mongodb+srv://yasin:cimbom21@cluster0.f8enl.mongodb.net/movie
  application:
    name: movie-catalog-service
server:
  port: 8000
  servlet:
    context-path: /api/movie-catalog-service
management:
  endpoints:
    web:
      base-path: /manage